### PR TITLE
Search page enhancement

### LINKED ISSUE #135: Add tags to Garden cards on search page
Entrypoints have tags associated with them. Gardens will have a compilation of these tags. 

1. Add the tags to the Garden cards on the search page. 
2. Style them to make them easy to read and sort through. (Like on [MDF](https://materialsdatafacility.org/portal) or [Foundry](https://foundry-ml.org/#/datasets) but with Garden styling)
3. Add tag search functionality: when I click on a tag, I see other Gardens with that tag. (Like what we have on the [MDF page](https://materialsdatafacility.org/portal))

### LINKED ISSUE #162: Search Page enhancements
Users should be able to filter search results
Apply more functions from Globus search to improve search result relevance and improve the search experience overall 
Redesign search result rendering + add more fields like authors, tags, doi, and more

### PR DESCRIPTION
**Pull request by shane-jung**
Implemented Globus search functionality with advanced filtering options

Added search result features including pagination, sorting, and customizable display options
Improved user interface and experience, with focus on responsive design and code optimization

### CODE REVIEW

**Comment by kjschmidt913** [comment]
@shane-jung can you take a look at the conflicts?

**Comment by shane-jung** [comment]
This should be good to go! @kjschmidt913

**Comment by kjschmidt913** [comment]
I'm still getting the message that there are conflicts, but i just merged in another PR so maybe that did it. Sorry!

**Comment by shane-jung** [comment]
Cool I think it should be fixed now!

**Pull request merged**
