### PR TITLE
Entrypoint page refactoring

### LINKED ISSUE #134: Switch to component library - Entrypoint Page
Switch the entrypoint page over to the new component library. Match styling in production as close as possible.

### PR DESCRIPTION
**Pull request by shane-jung**
Hi all, I wanted to get some feedback regarding some stylistic changes to the entrypoint page. Below are some screenshots, let me know if you have any suggestions. 

Some of the bigger changes I made were to the "Tabs" at the bottom of the page (Steps, Datasets, and Notebook) and the "Associated Materials" accordion. I also removed the "share" button for now, as that wasn't implemented previously (maybe that can be a future issue/PR). And then some small spacing/layout changes. Thanks!

Screenshot 2024-06-18 111136
Screenshot 2024-06-18 111144
Screenshot 2024-06-18 111156
Screenshot 2024-06-18 111451
Screenshot 2024-06-18 111509
Screenshot 2024-06-18 111601

### CODE REVIEW

**Comment by kjschmidt913** [comment]
Overall this looks great! I just have some styling things.

Is there a way to add more of the original styling back in? One of the reasons we went with this component library was because it was supposed to be easy to add our styling. I would really like the green on the tabs to come back.

The share button is working in production, so could you add that back?

The eyeball icon should be on the left side of "At a glance".

Could you remove the white background on the copy button on the test function?

**Comment by jamies31** [comment]
This looks really great to me! KJ covered most of what I had to say--but I was wondering if you were going to replace all the icons with similar ones from the component library. I know we were going for consistency, so I was wondering if you also replaced the icons everywhere else on the website, because the original ones were not from the component library, but from a Tailwind icon library. I agree with adding the green back on the tabs, since Garden already has a very limited color palette.

**Comment by shane-jung** [comment]
Thanks all! I made those changes and they are active on this branch if you want to take a look. 

Regarding the icons- the shadcn component library includes an icon library called [Lucide](https://lucide.dev/). Lucide has a good variety of icons that I feel should cover most of our needs. So far I have been going page by page to substitute our icons for the equivalent ones from Lucide (so far I've done home, search, and now entrypoint page). However, if there is an icon you want that you don't see within Lucide, we can always include the raw svg in our project. If you go this route, I think it makes sense to make a separate component file for that icon, just so we don't have to copy/paste these svg's around, and having raw SVGs in our React code tends to make the code a bit less readable. Hope that makes sense!

Last thing is the "associated materials" section. Here's how it looks on my branch: 
image

I made the github logo a bit smaller from production and adjusted some spacing. Let me know if you have any alternative preferences for this section. Thanks 😄

**Comment by jamies31** [comment]
The associated materials section looks good to me! Is the 'Visit Repository' button new?

**Comment by shane-jung** [comment]
> The associated materials section looks good to me! Is the 'Visit Repository' button new?

It's not new, I think most of the current gardens just don't have GitHub repos associated with them yet. Here's an example of what this section looks like in production:

image

**Comment by kjschmidt913** [comment]
@shane-jung I resolved merge conflicts in this PR. Can you take a look and make sure everything is running as you want it to?

**Comment by kjschmidt913** [comment]
Actually, I'll merge it into staging and we can preview there

**Pull request merged**
