### PR TITLE
User profile page - done, but working through build error

### PR DESCRIPTION
**Pull request by jamies31**
pretty much done with ui (at least the placement and styling of everything). Am currently working with backend to get the necessary fields and api routes created.

### CODE REVIEW

**Comment by kjschmidt913** [comment]
Screenshot 2024-07-01 at 11 06 46 AM

The build is failing, @jamies31 could you look into this error?

**Comment by kjschmidt913** [comment]
@jamies31 Could you name the PR something more descriptive so I know what this PR is about? Example: "Added metadata editing to entrypoint page", and then link to the related issues in the description. That will help me understand what's happening here :)

**Comment by jamies31** [comment]
Sorry about that! This PR isn't ready to review yet but it's for the user profile page, the title is just the last commit message I wrote which isn't too descriptive

**Comment by kjschmidt913** [comment]
Jamie is handling merge conflicts. We've decided to remove the saved gardens functionality (saved gardens tab on user profile page and save button on garden pages) and make that its own issue. Jamie would like to make the user icon in the navbar dropdown menu the user's profile icon they chose, but will be doing that at a later time

**Pull request merged**
